### ISSUE TITLE
Using Windows 10 shows error: 'TypeError: 'int' object is not subscriptable'

### ISSUE THREAD

**Issue by 00ninja** [tzlion/frogtool#4] opened 2023-05-17 13:09 UTC
I am having issues running frogtool.py under Windows 10 in VirtualBox under Linux Mint 20.3 using python 3.10+ and Pillow 9.5.0. This PC does not have an SD card reader so all files from SD are copied to a USB flash drive.

In a terminal, running 'frogtool.exe' shows the following error:

`Processing FC`
`Looking for files in E:/FC`
`Found image and zip files, looking for matches to combine to zfc`
`Traceback (most recent call last):`
`File "frogtool.py", line 375, in <module>`
`File "frogtool.py", line 363, in run`
`File "frogtool.py", line 111, in process_sys`
`File "frogtool.py", line 167, in convert_zip_image_pairs_to_zxx`
`File "frogtool.py", line 184, in convert_zip_image_to_zxx`
`File "frogtool.py", line 233, in rgb565_convert`
`TypeError: 'int' object is not subscriptable`
`[2468] Failed to execute script 'frogtool' due to unhandled exception!`

Running 'frogtool-0.2.0-py>python frogtool.py E: FC' gives similar error:

`Processing FC`
`Looking for files in E:/FC`
`Found image and zip files, looking for matches to combine to zfc`
`Traceback (most recent call last):`
`File "C:\Users\00ninja\Downloads\frogtool-0.2.0-py\frogtool.py", line 375, in <module> run()`
`File "C:\Users\00ninja\Downloads\frogtool-0.2.0-py\frogtool.py", line 363, in run process_sys(drive, syskey, test_mode)`
`File "C:\Users\00ninja\Downloads\frogtool-0.2.0-py\frogtool.py", line 111, in process_sys convert_zip_image_pairs_to_zxx(roms_path, system)`
`File "C:\Users\00ninja\Downloads\frogtool-0.2.0-py\frogtool.py", line 167, in convert_zip_image_pairs_to_zxx converted = convert_zip_image_to_zxx(roms_path, img_file, zip_file, sys_zxx_ext)`
`File "C:\Users\00ninja\Downloads\frogtool-0.2.0-py\frogtool.py", line 184, in convert_zip_image_to_zxx converted = rgb565_convert(img_file_path, zxx_file_path, (144, 208))`
`File "C:\Users\00ninja\Downloads\frogtool-0.2.0-py\frogtool.py", line 233, in rgb565_convert r = pixels[w, h][0] >> 3
TypeError: 'int' object is not subscriptable`

I am unsure if any of this has to do with the fact I am using a flash drive rather than an SD card, but all the right files are on the drive. 

While I would rather get frogtool.py running natively under linux, this report might prove useful. I did read that the TypeError is considered a 'stupid bug', or least the first result of my googlefi said that!

**Comment by EvanClements** [comment] 2023-05-23 14:33
I believe this issue and #3 are caused by the same thing.

**Comment by tzlion** [comment] 2023-05-23 17:37
Yeah @EvanClements I'll close #3 since that was originally about the windll issue which is fixed now, we can keep discussion of this issue over here.

Regarding your comment https://github.com/tzlion/frogtool/issues/3#issuecomment-1559535356 - do you know what the actual cause was/were you able to recreate it? I never could, but I pushed a commit to the `dev` branch to add some extra error checking at least - @00ninja you might want to try that version https://github.com/tzlion/frogtool/blob/dev/frogtool.py & see if it at least tells you which image it's failing on

**Comment by EvanClements** [comment] 2023-05-23 17:54
I did some Google-ing and came across a suggestion that using brackets to iterate over an array of integers can cause this error since brackets are also used to denote subscript (like in mathematical notation) when used with integer values.

I wasn't able to get the script to produce that error myself, but I was able to replace the brackets with the `.__getitem__(#)` code and it appears to be still working for me.

**Comment by tzlion** [comment] 2023-05-23 18:27
I think I found the problem after a bit more testing, it seems to occur if you have an image with indexed colour (e.g. a GIF or PNG8), I didn't realise that they wouldn't get converted automatically... testing a fix now

**Comment by tzlion** [comment] 2023-05-23 20:02
Should be fixed in v0.2.1 https://github.com/tzlion/frogtool/releases/tag/v0.2.1

**Closed by tzlion** 2023-05-23 20:02 UTC

**Comment by 00ninja** [comment] 2023-05-25 14:50
> Yeah @EvanClements I'll close #3 since that was originally about the windll issue which is fixed now, we can keep discussion of this issue over here.
> 
> Regarding your comment [#3 (comment)](https://github.com/tzlion/frogtool/issues/3#issuecomment-1559535356) - do you know what the actual cause was/were you able to recreate it? I never could, but I pushed a commit to the `dev` branch to add some extra error checking at least - @00ninja you might want to try that version https://github.com/tzlion/frogtool/blob/dev/frogtool.py & see if it at least tells you which image it's failing on

I used the dev version you suggested and all completed without problem. I went back, reset all of the resource files, and tried v0.2.1 again and all completed again without error. So I guess it was a glitch :/ Thanks again for fixes!
